INSERT INTO "public"."research_projects" ("id", "title", "description", "team_image_url", "social_link", "guide_name", "created_at") VALUES (1, 'AI for Gender Empowerment: Designing Inclusive and Bias-Aware Intelligent Systems', 'This research explores how Artificial Intelligence can serve as a catalyst for gender empowerment by identifying, analyzing, and addressing structural inequalities that persist within digital ecosystems. The study investigates the intersection of AI technologies, social inclusion, and gender equity, highlighting how intelligent systems can either mitigate or amplify existing disparities depending on design, data, and deployment choices. The work emphasizes gender-responsive AI frameworks, focusing on ethical model development, bias awareness, accessibility, and representation. Through practical case analysis, the research demonstrates how AI-driven solutions can enhance opportunities for women and underrepresented groups in areas such as education, decision-making, digital participation, and resource accessibility. It also evaluates challenges including algorithmic bias, data imbalance, and socio-technical barriers that influence equitable outcomes. Ultimately, the study advocates for responsible AI innovation where fairness, inclusivity, and human-centric design guide technological progress, ensuring that AI evolves as an instrument of empowerment rather than exclusion.', 'https://student-research-lab.vercel.app/assets/research1-De7lOjCv.png', 'https://www.linkedin.com/posts/mmpsrpc_svkm-ksv-mmpsrpc-activity-7429466085311098880-XDnV/', 'Dr. Himani Trivedi', '2026-02-23 02:18:53.197298'), (2, 'AI and Data-Driven Approaches for Predictive Healthcare and Risk Pattern Analysis', 'Paper 1: SHAP-Enhanced Outbreak Forecasting: Interpretable Multi-Modal Learning for Waterborne Disease Prediction
Presents an interpretable AI framework combining multi-modal data and SHAP analysis to improve transparency and accuracy in predicting waterborne disease outbreaks.

Paper 2: Enhancing Data Mining Techniques for Identifying Health Risk Patterns in Underserved Populations
Explores advanced data mining approaches to uncover hidden health risk patterns, supporting early intervention and informed decision-making in underserved communities.', 'https://student-research-lab.vercel.app/assets/research2-zu_DkMrD.png', 'https://www.linkedin.com/posts/mmpsrpc_ksv-svkm-mmpsrpc-activity-7407377566589759488-qigD/', 'Dr. Himani Trivedi', '2026-02-23 02:25:37.932492'), (3, 'Sustainability and Ethical Innovation: Research Contributions from KSV at the 9th NYC Green School Conference 2025', 'Faculty and student researchers from LDRP Institute of Technology & Research, Kadi Sarva Vishwavidyalaya (KSV), Gandhinagar, proudly represented the university at the 9th NYC Green School Conference 2025 held at Cornell University, New York. The conference provided an international platform for knowledge exchange and interdisciplinary dialogue on sustainability, ethical technology, and future-ready educational practices. The KSV delegation presented research spanning sustainable construction materials, ethical AI-based learning frameworks, and intelligent sustainability diagnostics for educational institutions. These contributions highlighted KSV’s commitment to impactful research, global academic collaboration, and innovation aligned with sustainable development goals. This initiative was made possible under the expert guidance and unwavering support of Dr. Jinal Joshi, Director, Department of International Relations, SVKM, whose mentorship played a pivotal role in facilitating this global opportunity. Participation at this prestigious global forum reflects the university’s growing international research footprint and dedication to fostering socially responsible, technology-driven solutions.

Paper 1: Hemp in Building: A Natural Step Toward Sustainable Construction
Focuses on the use of hemp as a sustainable construction material, exploring its properties, environmental benefits, and potential for green building applications.

Paper 2: Ethical AI and Gamified Pedagogy for Sustainable Classrooms
Explores the integration of ethical AI and gamification strategies to create engaging, sustainable, and inclusive learning environments.

Paper 3: EcoAudit AI: Sustainability Diagnostics & Resource Optimization in Smart Educational Institutions
Introduces an AI-driven system for sustainability audits and resource optimization, aimed at enhancing energy efficiency and environmental practices in educational institutions.', 'https://student-research-lab.vercel.app/assets/research3-Blv3wNVm.png', 'https://www.linkedin.com/posts/mmpsrpc_ksv-svkm-mmpsrpc-activity-7380831837272756224-XA7Q/', 'Dr. Jinal Joshi', '2026-02-23 02:31:14.989325'), (4, 'KSV Student Researchers Selected for Finale at National Poster Competition on AI Powered Research and Innovation', 'Students from LDRP Institute of Technology & Research, Kadi Sarva Vishwavidyalaya (KSV), Gandhinagar, under the guidance of the M. M. Patel Students Research Project Cell (MMPSRPC), have achieved a notable academic milestone by securing selection for the finale of the National Poster Competition on AI Powered Research and Innovation, organized by Gujarat Technological University (GTU), Ahmedabad. The competition, scheduled for 19th & 20th September 2025, brings together promising student researchers presenting innovative, technology-driven solutions addressing real-world challenges through Artificial Intelligence and data-centric methodologies.

Team 1: Bridging the Disconnect: Holistic Student Dropout Analysis in Schools through Data-Driven Machine Learning
This work presents a data-driven machine learning framework designed to analyze and predict student dropout risks through a holistic evaluation of academic, behavioral, and socio-economic indicators. By integrating multi-dimensional educational data, the study identifies hidden patterns and early warning signals associated with disengagement and attrition. The model emphasizes interpretability and practical usability, enabling educators and institutions to design timely, targeted interventions that improve retention, student support strategies, and overall learning outcomes.

Team 2: Tracking Air Pollution using INSAT Satellite and Ground Data Fusion
This study explores an integrated environmental monitoring approach that combines INSAT satellite observations with ground-based measurements to enhance air pollution assessment and tracking. Through data fusion techniques, the research improves spatial and temporal understanding of pollutant distribution, overcoming limitations of isolated sensing methods. The proposed framework supports more accurate pollution analysis, facilitating informed decision-making, environmental planning, and policy development aimed at sustainable urban management and public health protection.', 'https://student-research-lab.vercel.app/assets/research4-1-W6x_v6Xg.png , https://student-research-lab.vercel.app/assets/research4-2-Dy1uu-j4.png', 'https://www.linkedin.com/posts/mmpsrpc_gtu-airesearch-studentinnovation-activity-7376116498777616385-VT7i/', 'Dr. Himani Trivedi', '2026-02-23 02:35:44.408328');